### ISSUE TITLE
sporadic BindGroupLayout errors

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#855] opened 2024-09-18 05:04 UTC
After updating to the latest `wgpu@main` and `pygfx@main` I've been getting these sporadic errors. They are easiest to produce with the `line_plot.py` feature demo. 

Sometimes they occur when the scene is first shown, i.e. immediately upon running the example. And other times they occur after interacting with the scene for a while or resizing the window.

[wgpu-weird-2024-09-18_00.29.00.webm](https://github.com/user-attachments/assets/1e5f0ce2-f551-4c37-bf80-183af1864691)

A sample traceback when the scene is first shown:

```python
Draw error
Traceback (most recent call last):
  File "/home/kushal/repos/wgpu-py/wgpu/gui/_gui_utils.py", line 77, in log_exception
    yield
  File "/home/kushal/repos/wgpu-py/wgpu/gui/base.py", line 135, in _draw_frame_and_present
    self.draw_frame()
  File "/home/kushal/repos/pygfx/examples/feature_demo/line_plot.py", line 98, in animate
    renderer.render(scene, camera)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/renderer.py", line 531, in render
    command_buffers += self._render_recording(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/renderer.py", line 661, in _render_recording
    render_pass.end()
  File "/home/kushal/repos/wgpu-py/wgpu/backends/wgpu_native/_api.py", line 2950, in end
    libf.wgpuRenderPassEncoderEnd(self._internal)
  File "/home/kushal/repos/wgpu-py/wgpu/backends/wgpu_native/_helpers.py", line 329, in proxy_func
    raise wgpu_error  # the frame above is more interesting ↑↑
    ^^^^^^^^^^^^^^^^
wgpu._classes.GPUValidationError: Validation Error

Caused by:
  In wgpuRenderPassEncoderEnd
    In a draw command, kind: Draw
      The BindGroupLayout with '' label of current set BindGroup with '' label at index 0 is not compatible with the corresponding BindGroupLayout with '' label of RenderPipeline with '' label
        Entries with binding 3 differ in type: expected Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(16) }, got Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(12) }
        Entries with binding 4 differ in type: expected Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(32) }, got Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(24) }
        Entries with binding 5 differ in type: expected Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(16) }, got Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(12) }
```

A sample traceback when using the controller:

```python
Draw error
Traceback (most recent call last):
  File "/home/kushal/repos/wgpu-py/wgpu/gui/_gui_utils.py", line 77, in log_exception
    yield
  File "/home/kushal/repos/wgpu-py/wgpu/gui/base.py", line 135, in _draw_frame_and_present
    self.draw_frame()
  File "/home/kushal/repos/pygfx/examples/feature_demo/line_plot.py", line 98, in animate
    renderer.render(scene, camera)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/renderer.py", line 531, in render
    command_buffers += self._render_recording(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/renderer.py", line 661, in _render_recording
    render_pass.end()
  File "/home/kushal/repos/wgpu-py/wgpu/backends/wgpu_native/_api.py", line 2950, in end
    libf.wgpuRenderPassEncoderEnd(self._internal)
  File "/home/kushal/repos/wgpu-py/wgpu/backends/wgpu_native/_helpers.py", line 329, in proxy_func
    raise wgpu_error  # the frame above is more interesting ↑↑
    ^^^^^^^^^^^^^^^^
wgpu._classes.GPUValidationError: Validation Error

Caused by:
  In wgpuRenderPassEncoderEnd
    In a draw command, kind: Draw
      The BindGroupLayout with '' label of current set BindGroup with '' label at index 0 is not compatible with the corresponding BindGroupLayout with '' label of RenderPipeline with '' label
        Entries with binding 3 differ in type: expected Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(12) }, got Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(8) }
        Entries with binding 4 differ in type: expected Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(24) }, got Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(16) }
        Entries with binding 5 differ in type: expected Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(12) }, got Buffer { ty: Storage { read_only: true }, has_dynamic_offset: false, min_binding_size: Some(8) }
```

If I revert #852 then this disppears, but then the following error is produced when trying to run `mesh_slice.py`:

```python
Device::create_render_pipeline error: Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
Draw error
Traceback (most recent call last):
  File "/home/kushal/repos/wgpu-py/wgpu/gui/_gui_utils.py", line 77, in log_exception
    yield
  File "/home/kushal/repos/wgpu-py/wgpu/gui/base.py", line 135, in _draw_frame_and_present
    self.draw_frame()
  File "/home/kushal/repos/pygfx/examples/feature_demo/mesh_slice.py", line 59, in animate
    renderer.render(scene, camera)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/renderer.py", line 511, in render
    container_group = get_pipeline_container_group(wobject, environment)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 159, in get_pipeline_container_group
    pipeline_container_group.update(wobject, environment, changed_labels)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 239, in update
    container.update(wobject, environment, env_hash, changed)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 324, in update
    raise err
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 321, in update
    self.update_wgpu_data(environment, env_hash, changed)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 400, in update_wgpu_data
    env_pipelines[pass_index] = self._compose_pipeline(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 621, in _compose_pipeline
    return get_cached_render_pipeline(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 109, in get_cached_render_pipeline
    result = device.create_render_pipeline(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/wgpu-py/wgpu/backends/wgpu_native/_api.py", line 1765, in create_render_pipeline
    id = libf.wgpuDeviceCreateRenderPipeline(self._internal, struct)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/wgpu-py/wgpu/backends/wgpu_native/_helpers.py", line 329, in proxy_func
    raise wgpu_error  # the frame above is more interesting ↑↑
    ^^^^^^^^^^^^^^^^
wgpu._classes.GPUValidationError: Validation Error

Caused by:
  In wgpuDeviceCreateRenderPipeline
    Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
      Shader global ResourceBinding { group: 1, binding: 1 } is not available in the pipeline layout
        Buffer structure size 1120, added to one element of an unbound array, if it's the last field, ended up greater than the given `min_binding_size`, which is 560
Device::create_render_pipeline error: Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
Draw error: Validation Error (2)
```

`mesh_slice.py` only works with the fix in #852, but `line_plot.py` breaks with that fix :sweat_smile: 

wgpu info when running on my AMD GPU. I was also able to reproduce the issue on my Nvidia GPU.

```
██ system:

             platform:  Linux-5.10.0-21-amd64-x86_64-with-glibc2.31
python_implementation:  CPython
               python:  3.11.3

██ versions:

    wgpu:  0.18.1
    cffi:  1.16.0
    glfw:  2.7.0
   numpy:  2.0.1
   pygfx:  0.4.1
pylinalg:  0.4.1

██ wgpu_native_info:

expected_version:  22.1.0.5
     lib_version:  22.1.0.5
        lib_path:  ./resources/libwgpu_native-release.so

██ object_counts:

                      count  resource_mem

            Adapter:      1
          BindGroup:      0
    BindGroupLayout:      0
             Buffer:      2            40
      CanvasContext:      1
      CommandBuffer:      0
     CommandEncoder:      0
 ComputePassEncoder:      0
    ComputePipeline:      0
             Device:      1
     PipelineLayout:      0
           QuerySet:      0
              Queue:      1
       RenderBundle:      0
RenderBundleEncoder:      0
  RenderPassEncoder:      0
     RenderPipeline:      0
            Sampler:      0
       ShaderModule:      0
            Texture:      0
        TextureView:      0

              total:      6            40

██ wgpu_native_counts:

                  count    mem  backend   a  k  r  e  el_size

        Adapter:      1  2.03K   vulkan:  1  1  0  0    2.03K
      BindGroup:      0      0   vulkan:  0  0  0  0      368
BindGroupLayout:      0      0   vulkan:  0  0  0  0      320
         Buffer:      2    800   vulkan:  2  2  0  0      400
  CanvasContext:      1    592            1  1  0  0      592
  CommandBuffer:      0      0   vulkan:  0  0  0  0    1.04K
ComputePipeline:      0      0   vulkan:  0  0  0  0      288
         Device:      1  10.7K   vulkan:  1  1  0  0    10.7K
 PipelineLayout:      0      0   vulkan:  0  0  0  0      200
       QuerySet:      0      0   vulkan:  0  0  0  0       80
          Queue:      1    136   vulkan:  1  1  0  0      136
   RenderBundle:      0      0   vulkan:  0  0  0  0      848
 RenderPipeline:      0      0   vulkan:  0  0  0  0      560
        Sampler:      0      0   vulkan:  0  0  0  0       80
   ShaderModule:      0      0   vulkan:  0  0  0  0      808
        Texture:      0      0   vulkan:  0  0  0  0      888
    TextureView:      0      0   vulkan:  0  0  0  0      240

          total:      6  14.3K

    * The a, k, r, e are allocated, kept, released, and error, respectively.
    * Reported memory does not include buffer/texture data.

██ pygfx_adapter_info:

      vendor:  radv
architecture:
      device:  AMD RADV POLARIS10 (ACO)
 description:  Mesa 20.3.5 (ACO)
   vendor_id:  4.09K
   device_id:  26.5K
adapter_type:  DiscreteGPU
backend_type:  Vulkan

██ pygfx_features:

                                                                adapter  device

                                           depth-clip-control:        ✓       -
                                        depth32float-stencil8:        ✓       -
                                       texture-compression-bc:        ✓       -
                             texture-compression-bc-sliced-3d:        -       -
                                     texture-compression-etc2:        -       -
                                     texture-compression-astc:        -       -
                                              timestamp-query:        ✓       -
                                      indirect-first-instance:        ✓       -
                                                   shader-f16:        -       -
                                     rg11b10ufloat-renderable:        ✓       -
                                           bgra8unorm-storage:        -       -
                                           float32-filterable:        ✓       ✓
                                               clip-distances:        -       -
                                         dual-source-blending:        -       -
                                         buffer-binding-array:        ✓       -
                                     mappable-primary-buffers:        ✓       -
                                          multi-draw-indirect:        ✓       -
                                    multi-draw-indirect-count:        ✓       -
                                partially-bound-binding-array:        ✓       -
                                    pipeline-statistics-query:        ✓       -
                                               push-constants:        ✓       -
sampled-texture-and-storage-buffer-array-non-uniform-indexing:        ✓       -
                                                   shader-f64:        ✓       -
                                       shader-primitive-index:        ✓       -
                               storage-resource-binding-array:        ✓       -
                     texture-adapter-specific-format-features:        ✓       -
                                        texture-binding-array:        ✓       -
                                          texture-format-nv12:        ✓       -
                                     texture-format16bit-norm:        ✓       -
uniform-buffer-and-storage-texture-array-non-uniform-indexing:        ✓       -
                                      vertex-writable-storage:        ✓       -

██ pygfx_limits:

                                                  adapter  device

                                max-bind-groups:        8       8
            max-bind-groups-plus-vertex-buffers:        0       0
                    max-bindings-per-bind-group:    1.00K   1.00K
                                max-buffer-size:    2.14G   2.14G
          max-color-attachment-bytes-per-sample:        0       0
                          max-color-attachments:        0       0
          max-compute-invocations-per-workgroup:    1.02K   1.02K
                   max-compute-workgroup-size-x:    1.02K   1.02K
                   max-compute-workgroup-size-y:    1.02K   1.02K
                   max-compute-workgroup-size-z:    1.02K   1.02K
             max-compute-workgroup-storage-size:    32.7K   32.7K
           max-compute-workgroups-per-dimension:    65.5K   65.5K
max-dynamic-storage-buffers-per-pipeline-layout:        8       8
max-dynamic-uniform-buffers-per-pipeline-layout:       16      16
              max-inter-stage-shader-components:      128     128
               max-inter-stage-shader-variables:        0       0
                       max-non-sampler-bindings:    4.29G   1.00M
                         max-push-constant-size:      128     128
          max-sampled-textures-per-shader-stage:    8.38M   8.38M
                  max-samplers-per-shader-stage:    8.38M   8.38M
                max-storage-buffer-binding-size:    2.14G   2.14G
           max-storage-buffers-per-shader-stage:    8.38M   8.38M
          max-storage-textures-per-shader-stage:    8.38M   8.38M
                       max-texture-array-layers:    2.04K   2.04K
                        max-texture-dimension1d:    16.3K   16.3K
                        max-texture-dimension2d:    16.3K   16.3K
                        max-texture-dimension3d:    2.04K   2.04K
                max-uniform-buffer-binding-size:    2.14G   2.14G
           max-uniform-buffers-per-shader-stage:    8.38M   8.38M
                          max-vertex-attributes:       32      32
                 max-vertex-buffer-array-stride:    2.04K   2.04K
                             max-vertex-buffers:       16      16
            min-storage-buffer-offset-alignment:       32      32
            min-uniform-buffer-offset-alignment:       32      32

██ pygfx_caches:

                    count  hits  misses

full_quad_objects:      0     0       0
 mipmap_pipelines:      0     0       0
          layouts:      0     0       0
         bindings:      0     0       0
   shader_modules:      0     0       0
        pipelines:      0     0       0
 shadow_pipelines:      0     0       0

██ pygfx_resources:

Texture:  6
 Buffer:  25
```

**Comment by almarklein** [comment] 2024-09-18 10:02
Interesting! 🤔

**Comment by almarklein** [comment] 2024-09-18 10:09
Looks like `minBindingSize` can be 0 to avoid a check:
<img width="831" alt="image" src="https://github.com/user-attachments/assets/e307f3b0-ab32-4fe3-baee-21d8974e6e3d">

**Comment by panxinmiao** [comment] 2024-09-18 10:24
It seems to be the same intermittent CI error I encountered in #852.
﻿
I took a closer look, and this intermittent error appears to be related to the pipeline's caching mechanism. During `update_bind_groups`, the `binding_layout_des` changes—likely due to differences in `min_binding_size` introduced in #852. Occasionally, the pipeline does not rebuild correctly, though the exact cause is still unclear.
﻿

However, this also exposes another issue: #852 leads to a large number of unnecessary pipeline rebuilds in certain scenarios.
Let me explain.
﻿
When explicitly setting `min_binding_size`, this value must be greater than or equal to the size of the corresponding bound variable in the WGSL code. This differs for fixed-size arrays and runtime-sized arrays.
﻿
For example,` array<vec2f, 3>` requires a size of >= 24, which matches the `resource.nbytes`. Meanwhile, `array<vec2f>` only requires a size of >= 8, matching the `resource.itemSize`.
﻿
Of course, since `nbytes` is always greater than or equal to `itemSize`, using `nbytes` should technically meet the requirement. But the issue arises for runtime-sized arrays, where changes in the resource length trigger many unnecessary pipeline rebuilds (e.g., when updating `geometry.position`).
﻿
In essence, `min_binding_size` is determined by the shader code, and it’s difficult to infer directly from the resource (a ndarray). Currently, in pygfx, we always use fixed-length arrays for uniforms and runtime-sized arrays for storage buffers. So a quick fix might be possible here:
```python
  if "uniform" in self.type:
      min_binding_size = resource.nbytes
  else:
      min_binding_size = resource.itemsize
```
 but ultimately, this issue needs careful consideration and redesign.

**Comment by almarklein** [comment] 2024-09-18 10:32
Can you try #856 out?

**Comment by panxinmiao** [comment] 2024-09-18 11:17
> What do you think about simply setting it to 0? 

I believe it will work, even though the WebGPU documentation mentions that specifying its value can avoid checks during each draw command. However, for applications where extreme performance isn't the priority, this shouldn't be a significant issue.

That said, I also noticed some comments in the code and I'm unsure if the binding_layout object with the default min_binding_size can be compatible across different pipelines. If it's confirmed to be fine, I think it's ok :)

**Comment by almarklein** [comment] 2024-09-18 13:34
> That said, I also noticed some comments in the code and I'm unsure if the binding_layout object with the default min_binding_size can be compatible across different buffers(I guess it can, but I can't be entirely sure, 😅 ).

Yeah, that's the part I'm a bit worried about. I can't remember the situation, but the fact that I wrote that down is an indication that *at the time* the layouts were *not* compatible. Maybe this changed ...

>  If it's confirmed to be fine, I think it's ok :)

I ran the examples and the tests. But that may not be enough to trigger the use-case :)

**Comment by kushalkolar** [comment] 2024-09-18 23:05
I can confirm that #856 fixes it! Will leave this open in case I see it again over the next few days

**Comment by almarklein** [comment] 2024-09-19 07:11
Ok, let's also do a release then :)

**Comment by almarklein** [comment] 2024-09-19 07:19
> Will leave this open in case I see it again over the next few days

I prefer to close it, and reopen if the error resurfaces.

**Closed by almarklein** 2024-09-19 07:19 UTC
