### ISSUE TITLE
Performance tweaks to the wgpu renderer

### ISSUE THREAD

**Issue by almarklein** [pygfx/pygfx#164] opened 2021-10-07 19:31 UTC
* Could make more use of caching in the renderer. There are some todo's indicating possible locations.
* ~We could re-use the command queue instead of recording it on each draw.~ Could use render bundles.

Related: #322

**Comment by Korijn** [comment] 2023-03-24 09:57
Closing this as a duplicate of #322

**Closed by Korijn** 2023-03-24 09:57 UTC
Labels: enhancement
